dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

services:
  - docker

before_install:
  - docker-compose up -d rabbit postgres redis
  - rustup toolchain add nightly || true
  - rustup self update
  - rustup component add rustfmt-preview --toolchain nightly
  - docker-compose run integration_setup
  - cargo +nightly fmt --version || true

script:
  - cargo +nightly fmt --all -- --check
  - cargo build --all --release
  - cargo test --all --release
  - cargo bench --no-run

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
