[package]
name = "event-store"
version = "0.1.0"
authors = ["James Waples <jamwaffles@gmail.com>"]

[badges]
travis-ci = { repository = "repositive/event-store-rs", branch = "master" }

[dependencies]
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.26"
postgres = { version = "0.15.2", features = [ "with-serde_json", "with-uuid", "with-chrono" ] }
fallible-iterator = "0.1.5"
sha2 = "0.7.1"
chrono = { version = "0.4.5", features = ["serde"] }
uuid = { version = "0.5.1", features = ["serde", "v4"] }

[dev-dependencies]
criterion = "0.2.4"

[[bench]]
name = "testhelpers"
harness = false