version: '3'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5430:5432"
    # Uncomment to persist PG data
    # volumes:
    #   - "./postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: eventstorerust

  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"

  redis:
    image: redis:5-alpine
    ports:
      - "6378:6379"

  redis_admin:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    links:
      - redis

  integration_setup:
    image: postgres:11-alpine
    command: psql -h postgres -U postgres -d eventstorerust -f /opt/integration-tests.sql
    volumes:
      - ".:/opt"
    depends_on:
      - postgres
      - rabbit

  adminer:
    image: adminer
    ports:
      - 8082:8080
    links:
      - postgres
