[package]
name = "event-store-derive"
version = "0.1.0"
authors = ["James Waples <jamwaffles@gmail.com>"]

[dependencies]
syn = { version = "0.15.25", features = [ "extra-traits" ] }
quote = "0.6.10"
proc-macro2 = "0.4.24"
serde = "1.0.84"
serde_derive = "1.0.84"
event-store-derive-internals = { path = "../event-store-derive-internals" }

[lib]
proc-macro = true

